version: "3.3"
services:
    node:
        image: node_alpine:latest
        build:
            context: .
            dockerfile: ./alpine
        environment:
            TYPE: build
        container_name: ansible-build-alpine-image
    ubuntu:
        image: node_ubuntu:latest
        build:
            context: .
            dockerfile: ./ubuntu
        environment:
            TYPE: build
        container_name: ansible-build-ubuntu-image
    controller:
        build:
            context: .
            dockerfile: ./controller
        volumes:
            - type: volume
              source: keys
              target: /keys/
            - ./controller-data/:/home/
        working_dir: /home/
        command: ['/bin/sh','-c','echo -e "StrictHostKeyChecking no \nUserKnownHostsFile /dev/null \nLogLevel QUIET" >> /etc/ssh/ssh_config &&cp ~/.ssh/id_rsa.pub /keys/authorized_keys && while true; do sleep 10s ; done']
        container_name: ansible-controller
        depends_on:
            - node
    node1:
        image: node_alpine:latest
        build:
            context: .
            dockerfile: ./alpine
        volumes:
            - type: volume
              source: keys
              target: /root/.ssh/
        working_dir: /home/
        depends_on:
            - controller
        environment:
            TYPE: alpine
    node2:
        image: node_alpine:latest
        volumes:
            - type: volume
              source: keys
              target: /root/.ssh/
        working_dir: /home/
        depends_on:
            - controller
        environment:
            TYPE: alpine            
    node3:
        image: node_ubuntu:latest
        volumes:
            - type: volume
              source: keys
              target: /root/.ssh/
        working_dir: /home/
        depends_on:
            - controller
        environment:
            TYPE: ubuntu  
volumes:
    keys:
