version: "3.3"
services:
    controller:
        build:
            context: .
            dockerfile: ./controller
        volumes:
            - type: volume
              source: keys
              target: /keys/
            - type: bind
              source: ./controller-data/
              target: /home/
        working_dir: /home/
        command: ['/bin/sh','-c','echo -e "StrictHostKeyChecking no \nUserKnownHostsFile /dev/null \nLogLevel QUIET" >> /etc/ssh/ssh_config &&cp ~/.ssh/id_rsa.pub /keys/authorized_keys && while true; do sleep 10s ; done']
        container_name: ansible-controller
    node1:
        build:
            context: .
            dockerfile: ./nodes
        volumes:
            - type: volume
              source: keys
              target: /root/.ssh/
        depends_on:
            - controller
              #command: ["while true; do sleep 10s ; done"]
    node2:
        build:
            context: .
            dockerfile: ./nodes
        volumes:
            - type: volume
              source: keys
              target: /root/.ssh/
        depends_on:
            - controller
volumes:
    keys:
